/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import DataBaseLayer.DataBaseConnection;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

public class Manage_Inv extends javax.swing.JInternalFrame {

    public Manage_Inv() {
        initComponents();
    }
    private Statement st;
    private ResultSet rs;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnadd = new javax.swing.JButton();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        btn_Invetory_view1 = new javax.swing.JButton();
        txtitemname = new javax.swing.JTextField();
        txtqty2 = new javax.swing.JTextField();
        txtunitprice = new javax.swing.JTextField();
        txtitemcode = new javax.swing.JTextField();
        btnadd1 = new javax.swing.JButton();
        txtsupplier = new javax.swing.JTextField();
        txt_pidinvntory = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setIconifiable(true);
        setTitle("Manage Inventory");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Images/asset-2.png"))); // NOI18N
        setMinimumSize(new java.awt.Dimension(738, 426));
        setPreferredSize(new java.awt.Dimension(738, 426));

        jPanel1.setBackground(java.awt.Color.darkGray);
        jPanel1.setMaximumSize(new java.awt.Dimension(950, 700));
        jPanel1.setMinimumSize(new java.awt.Dimension(950, 700));
        jPanel1.setPreferredSize(new java.awt.Dimension(950, 800));

        btnadd.setBackground(new java.awt.Color(255, 255, 255));
        btnadd.setText("Update Details");
        btnadd.setMaximumSize(new java.awt.Dimension(140, 47));
        btnadd.setMinimumSize(new java.awt.Dimension(140, 47));
        btnadd.setPreferredSize(new java.awt.Dimension(140, 47));
        btnadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddActionPerformed(evt);
            }
        });

        jLabel33.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(255, 255, 255));
        jLabel33.setText("Item Code");

        jLabel34.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(255, 255, 255));
        jLabel34.setText("Name");

        jLabel35.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(255, 255, 255));
        jLabel35.setText("QTY");

        jLabel37.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(255, 255, 255));
        jLabel37.setText(" Suplier ID");

        jLabel38.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(255, 255, 255));
        jLabel38.setText(" Unit Price");

        btn_Invetory_view1.setBackground(new java.awt.Color(255, 255, 255));
        btn_Invetory_view1.setText("Delete Details");
        btn_Invetory_view1.setMaximumSize(new java.awt.Dimension(140, 47));
        btn_Invetory_view1.setMinimumSize(new java.awt.Dimension(140, 47));
        btn_Invetory_view1.setPreferredSize(new java.awt.Dimension(140, 47));
        btn_Invetory_view1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Invetory_view1ActionPerformed(evt);
            }
        });

        txtqty2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtqty2ActionPerformed(evt);
            }
        });

        txtunitprice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtunitpriceActionPerformed(evt);
            }
        });

        btnadd1.setBackground(new java.awt.Color(255, 255, 255));
        btnadd1.setText("Search");
        btnadd1.setMaximumSize(new java.awt.Dimension(140, 47));
        btnadd1.setMinimumSize(new java.awt.Dimension(140, 47));
        btnadd1.setPreferredSize(new java.awt.Dimension(140, 47));
        btnadd1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnadd1ActionPerformed(evt);
            }
        });

        txtsupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsupplierActionPerformed(evt);
            }
        });

        txt_pidinvntory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_pidinvntoryActionPerformed(evt);
            }
        });

        jLabel36.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(255, 255, 255));
        jLabel36.setText("PID");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel38)
                    .addComponent(jLabel37)
                    .addComponent(jLabel35)
                    .addComponent(jLabel34)
                    .addComponent(jLabel33)
                    .addComponent(jLabel36))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(txtunitprice, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(txtsupplier, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(233, 233, 233)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_Invetory_view1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnadd, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_pidinvntory, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtitemname, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtqty2, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(txtitemcode, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnadd1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtitemname, txtqty2, txtunitprice});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btn_Invetory_view1, btnadd});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(btnadd1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtitemcode, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(13, 13, 13)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnadd, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_Invetory_view1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel34)
                                    .addComponent(txtitemname, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(27, 27, 27)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtqty2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel35))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txt_pidinvntory, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel36))
                                .addGap(26, 26, 26)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel37)
                                    .addComponent(txtsupplier, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(27, 27, 27)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtunitprice, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel38)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jLabel33)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btn_Invetory_view1, btnadd});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 726, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtunitpriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtunitpriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtunitpriceActionPerformed

    private void txtqty2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtqty2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtqty2ActionPerformed

    private void btn_Invetory_view1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Invetory_view1ActionPerformed
        try {
            try {
                Connection con = DataBaseConnection.getDBconnection();
                String queryup = "UPDATE inventory SET Status=? where Itemcode='" + txtitemcode.getText() + "'";
                PreparedStatement pst = con.prepareStatement(queryup);

                pst.setInt(1, 0);

                pst.executeUpdate();
                JOptionPane.showMessageDialog(null, "Deleted Successfully");

            } catch (StringIndexOutOfBoundsException e) {
                JOptionPane.showMessageDialog(null, "Please fill the required fields");
            }

        } catch (Exception e) {
            System.out.println(e);
            JOptionPane.showMessageDialog(null, "Error Occured");
        }


    }//GEN-LAST:event_btn_Invetory_view1ActionPerformed

    private void btnaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddActionPerformed
        try {
            try {
                Connection con = DataBaseConnection.getDBconnection();
                String queryup = "UPDATE inventory SET Itemcode=?, PID=?, SupplierID=?, Name=?, Qty=?, Unitprice=? where Itemcode='" + txtitemcode.getText() + "'";
                PreparedStatement pst = con.prepareStatement(queryup);

                String itemname = txtitemname.getText();
                String supplier = txtsupplier.getText();
                String pidinventory = txt_pidinvntory.getText();
                if ((itemname.equals("")) || (supplier.equals("")) || (pidinventory.equals(""))) {

                    JOptionPane.showMessageDialog(null, "Error");
                } else {

                    pst.setString(1, txtitemcode.getText());
                    pst.setString(2, txt_pidinvntory.getText());
                    pst.setString(3, txtsupplier.getText());
                    pst.setString(4, txtitemname.getText());
                    pst.setInt(5, Integer.parseInt(txtqty2.getText()));
                    pst.setInt(6, Integer.parseInt(txtunitprice.getText()));

                    pst.executeUpdate();
                    JOptionPane.showMessageDialog(null, "Updated Successfully");

                }

            } catch (StringIndexOutOfBoundsException e) {
                JOptionPane.showMessageDialog(null, "Please fill the required fields");
            }

        } catch (Exception e) {
            System.out.println(e);
            JOptionPane.showMessageDialog(null, "Error Occured");
        }


    }//GEN-LAST:event_btnaddActionPerformed

    private void btnadd1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnadd1ActionPerformed
        // TODO add your handling code here:

        try {

            Connection con = DataBaseConnection.getDBconnection();

            String query = "select Itemcode,PID,SupplierID,Name,Qty,Unitprice from inventory where Itemcode='" + txtitemcode.getText() + "'";

            st = con.prepareStatement(query);
            st = con.createStatement();
            rs = st.executeQuery(query);

            if (rs.next()) {
                txtitemcode.setText(txtitemcode.getText());
                txt_pidinvntory.setText(rs.getString(2));
                txtsupplier.setText(rs.getString(3));
                txtitemname.setText(rs.getString(4));
                txtqty2.setText(rs.getString(5));
                txtunitprice.setText(rs.getString(6));

            }

        } catch (Exception e) {

            JOptionPane.showMessageDialog(null, e);
        }


    }//GEN-LAST:event_btnadd1ActionPerformed

    private void txtsupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsupplierActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsupplierActionPerformed

    private void txt_pidinvntoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_pidinvntoryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_pidinvntoryActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Manage_Inv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Manage_Inv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Manage_Inv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Manage_Inv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Manage_Inv().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Invetory_view1;
    private javax.swing.JButton btnadd;
    private javax.swing.JButton btnadd1;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txt_pidinvntory;
    private javax.swing.JTextField txtitemcode;
    private javax.swing.JTextField txtitemname;
    private javax.swing.JTextField txtqty2;
    private javax.swing.JTextField txtsupplier;
    private javax.swing.JTextField txtunitprice;
    // End of variables declaration//GEN-END:variables
}
