/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import DataBaseLayer.DataBaseConnection;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;

public class Manage_Employee extends javax.swing.JInternalFrame {

    /**
     * Creates new form GUI
     */
    private void groupButton() {
        ButtonGroup bg1 = new ButtonGroup();
        bg1.add(rdo_ManageEmp_Gender_male);
        bg1.add(rdo_ManageEmp_Gender_female);

    }

    private void groupbutton1() {
        ButtonGroup bg2 = new ButtonGroup();
        bg2.add(rdo_ManageEmp_Status_Married);
        bg2.add(rdo_ManageEmp_Status_Single);

    }

    public Manage_Employee() {
        initComponents();
        groupButton();
        groupbutton1();

    }
    private String url;
    private Connection conDB;
    private Statement st;
    private byte[] person_img;
    private String filename = null;
    private ResultSet rs;
    private int marital;
    private String maritalof;
    private int gender;
    private String genderof;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel6 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        txt_ManageEmp_Bsalary = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        txt_ManageEmp_Address_Street = new javax.swing.JTextField();
        txt_ManageEmp_Address_City = new javax.swing.JTextField();
        txt_ManageEmp_Lname = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        btn_ManageEmp_Update = new javax.swing.JButton();
        txt_ManageEmp_Fname = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        txt_ManageEmp_Address_Number = new javax.swing.JTextField();
        rdo_ManageEmp_Status_Married = new javax.swing.JRadioButton();
        rdo_ManageEmp_Status_Single = new javax.swing.JRadioButton();
        rdo_ManageEmp_Gender_male = new javax.swing.JRadioButton();
        rdo_ManageEmp_Gender_female = new javax.swing.JRadioButton();
        lblID1 = new javax.swing.JLabel();
        lblName1 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        txt_ManageEmp_ContactNo = new javax.swing.JTextField();
        txt_ManageEmp_Email = new javax.swing.JTextField();
        btn_ManageEmp_Delete = new javax.swing.JButton();
        cmb_ManageEmp_Position = new javax.swing.JComboBox<>();
        btn_attendance_empID_Search = new javax.swing.JButton();
        txt_id = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setResizable(true);
        setMinimumSize(new java.awt.Dimension(962, 560));

        jTabbedPane1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jTabbedPane1.setMinimumSize(new java.awt.Dimension(962, 560));
        jTabbedPane1.setPreferredSize(new java.awt.Dimension(962, 560));
        jTabbedPane1.setVerifyInputWhenFocusTarget(false);

        jPanel6.setBackground(java.awt.Color.darkGray);

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Basic Salary");

        txt_ManageEmp_Bsalary.setBorder(null);

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Number");

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Street");

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("City");

        txt_ManageEmp_Address_Street.setBorder(null);

        txt_ManageEmp_Address_City.setBorder(null);

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Last Name");

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Email");

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Status");

        btn_ManageEmp_Update.setBackground(new java.awt.Color(255, 255, 255));
        btn_ManageEmp_Update.setText("Update Details");
        btn_ManageEmp_Update.setBorder(null);
        btn_ManageEmp_Update.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_ManageEmp_Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ManageEmp_UpdateActionPerformed(evt);
            }
        });

        txt_ManageEmp_Fname.setBorder(null);
        txt_ManageEmp_Fname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_ManageEmp_FnameActionPerformed(evt);
            }
        });

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("Position");

        txt_ManageEmp_Address_Number.setBorder(null);

        rdo_ManageEmp_Status_Married.setBackground(new java.awt.Color(44, 62, 80));
        rdo_ManageEmp_Status_Married.setForeground(new java.awt.Color(255, 255, 255));
        rdo_ManageEmp_Status_Married.setText("Married");
        rdo_ManageEmp_Status_Married.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdo_ManageEmp_Status_MarriedActionPerformed(evt);
            }
        });

        rdo_ManageEmp_Status_Single.setBackground(new java.awt.Color(44, 62, 80));
        rdo_ManageEmp_Status_Single.setForeground(new java.awt.Color(255, 255, 255));
        rdo_ManageEmp_Status_Single.setText("Single");
        rdo_ManageEmp_Status_Single.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdo_ManageEmp_Status_SingleActionPerformed(evt);
            }
        });

        rdo_ManageEmp_Gender_male.setBackground(new java.awt.Color(44, 62, 80));
        rdo_ManageEmp_Gender_male.setForeground(new java.awt.Color(255, 255, 255));
        rdo_ManageEmp_Gender_male.setText("Male");

        rdo_ManageEmp_Gender_female.setBackground(new java.awt.Color(44, 62, 80));
        rdo_ManageEmp_Gender_female.setForeground(new java.awt.Color(255, 255, 255));
        rdo_ManageEmp_Gender_female.setText("Female");
        rdo_ManageEmp_Gender_female.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdo_ManageEmp_Gender_femaleActionPerformed(evt);
            }
        });

        lblID1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblID1.setForeground(new java.awt.Color(255, 255, 255));
        lblID1.setText("ID");

        lblName1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblName1.setForeground(new java.awt.Color(255, 255, 255));
        lblName1.setText("First Name");

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("Address");

        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("Gender");

        jLabel29.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setText("Contact Number");

        txt_ManageEmp_ContactNo.setBorder(null);

        txt_ManageEmp_Email.setBorder(null);

        btn_ManageEmp_Delete.setBackground(new java.awt.Color(255, 255, 255));
        btn_ManageEmp_Delete.setText("Delete Details");
        btn_ManageEmp_Delete.setBorder(null);
        btn_ManageEmp_Delete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_ManageEmp_Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ManageEmp_DeleteActionPerformed(evt);
            }
        });

        cmb_ManageEmp_Position.setEditable(true);
        cmb_ManageEmp_Position.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Labourer", "Supervisor", "Manager", "Administrator" }));
        cmb_ManageEmp_Position.setBorder(null);
        cmb_ManageEmp_Position.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cmb_ManageEmp_PositionKeyPressed(evt);
            }
        });

        btn_attendance_empID_Search.setBackground(new java.awt.Color(255, 255, 255));
        btn_attendance_empID_Search.setText("Search");
        btn_attendance_empID_Search.setBorder(null);
        btn_attendance_empID_Search.setMaximumSize(new java.awt.Dimension(35, 35));
        btn_attendance_empID_Search.setMinimumSize(new java.awt.Dimension(35, 35));
        btn_attendance_empID_Search.setPreferredSize(new java.awt.Dimension(35, 35));
        btn_attendance_empID_Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_attendance_empID_SearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblID1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblName1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel24, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel27, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel28, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel29, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel23, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(rdo_ManageEmp_Status_Married)
                        .addGap(18, 18, 18)
                        .addComponent(rdo_ManageEmp_Status_Single))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txt_ManageEmp_Fname, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addComponent(txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btn_attendance_empID_Search, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGap(90, 90, 90)
                                .addComponent(jLabel21))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_ManageEmp_Email, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_ManageEmp_ContactNo, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addComponent(rdo_ManageEmp_Gender_male)
                                        .addGap(18, 18, 18)
                                        .addComponent(rdo_ManageEmp_Gender_female)))))
                        .addGap(33, 33, 33)
                        .addComponent(txt_ManageEmp_Lname, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(201, Short.MAX_VALUE))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(136, 136, 136)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel20, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_ManageEmp_Address_City, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_ManageEmp_Address_Street, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_ManageEmp_Address_Number, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel25, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(txt_ManageEmp_Bsalary, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addComponent(cmb_ManageEmp_Position, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(417, 417, 417)))
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btn_ManageEmp_Delete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_ManageEmp_Update, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(78, 78, 78))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblID1)
                    .addComponent(btn_attendance_empID_Search, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblName1)
                    .addComponent(txt_ManageEmp_Fname, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_ManageEmp_Lname, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21))
                .addGap(32, 32, 32)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(rdo_ManageEmp_Status_Married)
                    .addComponent(rdo_ManageEmp_Status_Single))
                .addGap(18, 18, 18)
                .addComponent(jLabel27)
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_ManageEmp_Address_Number, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_ManageEmp_Address_Street, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_ManageEmp_Address_City, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20))
                .addGap(32, 32, 32)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(rdo_ManageEmp_Gender_male)
                    .addComponent(rdo_ManageEmp_Gender_female))
                .addGap(22, 22, 22)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(txt_ManageEmp_ContactNo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(txt_ManageEmp_Email, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(txt_ManageEmp_Bsalary, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmb_ManageEmp_Position, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(btn_ManageEmp_Update, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_ManageEmp_Delete, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(126, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel6);

        jTabbedPane1.addTab("Manage Employee", jScrollPane1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rdo_ManageEmp_Status_MarriedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdo_ManageEmp_Status_MarriedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdo_ManageEmp_Status_MarriedActionPerformed

    private void txt_ManageEmp_FnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_ManageEmp_FnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_ManageEmp_FnameActionPerformed

    private void rdo_ManageEmp_Status_SingleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdo_ManageEmp_Status_SingleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdo_ManageEmp_Status_SingleActionPerformed

    private void btn_attendance_empID_SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_attendance_empID_SearchActionPerformed
        /*search button*/

        try {

            Connection con = DataBaseConnection.getDBconnection();

            String query = "select EmployeeID,Firstname,Lastname,MaritalStatus,HouseNo,Street,City,Gender,ContactNo,Email,Position,BasicSalary from employees where EmployeeID='" + txt_id.getText() + "'";

            st = con.prepareStatement(query);
            st = con.createStatement();
            rs = st.executeQuery(query);

            if (rs.next()) {
                txt_id.setText(txt_id.getText());
                txt_ManageEmp_Fname.setText(rs.getString(2));

                txt_ManageEmp_Lname.setText(rs.getString(3));
                String no = Integer.toString(rs.getInt(5));

                txt_ManageEmp_Address_Number.setText(no);

                txt_ManageEmp_Address_Street.setText(rs.getString(6));
                txt_ManageEmp_Address_City.setText(rs.getString(7));
                txt_ManageEmp_Email.setText(rs.getString(10));
                txt_ManageEmp_ContactNo.setText(rs.getString(9));
                // txt_ManageEmp_DOB.setText(rs.getString(9));
                String gender = rs.getString(8);

                if (gender.equals("male")) {
                    rdo_ManageEmp_Gender_male.setSelected(true);
                }

                if (gender.equals("female")) {
                    rdo_ManageEmp_Gender_female.setSelected(true);
                }

                String marital = rs.getString(4);

                if (marital.equals("married")) {
                    rdo_ManageEmp_Status_Married.setSelected(true);
                }
                if (marital.equals("unmarried")) {
                    rdo_ManageEmp_Status_Single.setSelected(true);
                }

                int s = rs.getInt(12);
                String sala = Integer.toString(s);

                txt_ManageEmp_Bsalary.setText(sala);

                cmb_ManageEmp_Position.setSelectedItem(rs.getString(11));

            } else {
                JOptionPane.showMessageDialog(null, "Employee Number Is Invalid.");
            }

        } catch (Exception e) {

            JOptionPane.showMessageDialog(null, e);
        }


    }//GEN-LAST:event_btn_attendance_empID_SearchActionPerformed

    private void btn_ManageEmp_UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ManageEmp_UpdateActionPerformed
        // TODO add your handling code here:
        try {
            try {
                Connection con = DataBaseConnection.getDBconnection();
                String queryup = "UPDATE employees SET EmployeeID=?, FirstName=?, LastName=?, HouseNo=?, Street=?, City=?, Email=?, ContactNo=?, Gender=?, MaritalStatus=?, Position=?, BasicSalary=?, Status=? where EmployeeID='" + txt_id.getText() + "'";
                PreparedStatement pst = con.prepareStatement(queryup);

                String idq = txt_id.getText();
                String i1 = idq.substring(0, 1);

                String Firstn = txt_ManageEmp_Fname.getText();
                String Lastn = txt_ManageEmp_Lname.getText();
                String n = txt_ManageEmp_Address_Number.getText();
                String street = txt_ManageEmp_Address_Street.getText();
                String city = txt_ManageEmp_Address_City.getText();
                String connum = txt_ManageEmp_ContactNo.getText();
                int s1 = connum.length();
                String emaill = txt_ManageEmp_Email.getText();
                String marital = null;
                String gender = null;

                String positions = cmb_ManageEmp_Position.getSelectedItem().toString();

                if ((Firstn.equals("")) || (Lastn.equals("")) || (street.equals("")) || (city.equals(""))) {
                    JOptionPane.showMessageDialog(null, "Error Occured");
                } else {

                    pst.setString(1, txt_id.getText());
                    pst.setString(2, txt_ManageEmp_Fname.getText());
                    pst.setString(3, txt_ManageEmp_Lname.getText());
                    pst.setString(4, txt_ManageEmp_Address_Number.getText());
                    pst.setString(5, txt_ManageEmp_Address_Street.getText());
                    pst.setString(6, txt_ManageEmp_Address_City.getText());
                    pst.setString(8, txt_ManageEmp_ContactNo.getText());
                    pst.setString(7, txt_ManageEmp_Email.getText());

                    if (rdo_ManageEmp_Status_Married.isSelected()) {
                        marital = "married";

                    } else {
                        if (rdo_ManageEmp_Status_Single.isSelected()) {
                            marital = "unmarried";

                        }
                    }

                    if (rdo_ManageEmp_Gender_male.isSelected()) {

                        gender = "male";
                    }
                    if (rdo_ManageEmp_Gender_female.isSelected()) {

                        gender = "female";
                    }
                    pst.setString(9, gender);
                    pst.setString(10, marital);
                    String position1;
                    position1 = cmb_ManageEmp_Position.getSelectedItem().toString();
                    pst.setString(11, position1);

                    String er = txt_ManageEmp_Bsalary.getText();
                    int q = Integer.parseInt(er);
                    pst.setInt(12, q);

                    pst.setInt(13, 1);

                    // String l=image.getText();
                    pst.executeUpdate();
                    JOptionPane.showMessageDialog(null, "Updated Successfully");

                }

            } catch (StringIndexOutOfBoundsException e) {
                JOptionPane.showMessageDialog(null, "Please fill the required fields");
            }

        } catch (Exception e) {
            System.out.println(e);
            JOptionPane.showMessageDialog(null, "Error Occured");
        }


    }//GEN-LAST:event_btn_ManageEmp_UpdateActionPerformed

    private void btn_ManageEmp_DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ManageEmp_DeleteActionPerformed
        // TODO add your handling code here:

        try {
            Connection con = DataBaseConnection.getDBconnection();
            String queryup = "UPDATE employees SET Status=? where EmployeeID='" + txt_id.getText() + "'";
            PreparedStatement pst = con.prepareStatement(queryup);

            pst.setInt(1, 0);

            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Deleted Successfully");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }

    }

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:


    }//GEN-LAST:event_btn_ManageEmp_DeleteActionPerformed

    private void cmb_ManageEmp_PositionKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cmb_ManageEmp_PositionKeyPressed
        String tc = cmb_ManageEmp_Position.getSelectedItem().toString();

    }//GEN-LAST:event_cmb_ManageEmp_PositionKeyPressed

    private void rdo_ManageEmp_Gender_femaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdo_ManageEmp_Gender_femaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdo_ManageEmp_Gender_femaleActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Manage_Employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Manage_Employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Manage_Employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Manage_Employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new Manage_Employee().setVisible(true);
                new Login().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_ManageEmp_Delete;
    private javax.swing.JButton btn_ManageEmp_Update;
    private javax.swing.JButton btn_attendance_empID_Search;
    private javax.swing.JComboBox<String> cmb_ManageEmp_Position;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblID1;
    private javax.swing.JLabel lblName1;
    private javax.swing.JRadioButton rdo_ManageEmp_Gender_female;
    private javax.swing.JRadioButton rdo_ManageEmp_Gender_male;
    private javax.swing.JRadioButton rdo_ManageEmp_Status_Married;
    private javax.swing.JRadioButton rdo_ManageEmp_Status_Single;
    private javax.swing.JTextField txt_ManageEmp_Address_City;
    private javax.swing.JTextField txt_ManageEmp_Address_Number;
    private javax.swing.JTextField txt_ManageEmp_Address_Street;
    private javax.swing.JTextField txt_ManageEmp_Bsalary;
    private javax.swing.JTextField txt_ManageEmp_ContactNo;
    private javax.swing.JTextField txt_ManageEmp_Email;
    private javax.swing.JTextField txt_ManageEmp_Fname;
    private javax.swing.JTextField txt_ManageEmp_Lname;
    private javax.swing.JTextField txt_id;
    // End of variables declaration//GEN-END:variables
}
