/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import DataBaseLayer.DataBaseConnection;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

public class Manage_Sup extends javax.swing.JInternalFrame {

    public Manage_Sup() {
        initComponents();

    }
    private Statement st;
    private ResultSet rs;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        btnadd2 = new javax.swing.JButton();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        btn_Invetory_view5 = new javax.swing.JButton();
        txt_Supplier_name = new javax.swing.JTextField();
        txt_Supplier_cNo = new javax.swing.JTextField();
        txt_Supplier_Email = new javax.swing.JTextField();
        txt_Supplier_Address = new javax.swing.JTextField();
        txt_Supplier_SID = new javax.swing.JTextField();
        btnadd5 = new javax.swing.JButton();
        cmb_Supplier_Add = new javax.swing.JComboBox<>();
        jLabel49 = new javax.swing.JLabel();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setIconifiable(true);
        setTitle("Manage Inventory");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Images/asset-2.png"))); // NOI18N
        setMinimumSize(new java.awt.Dimension(950, 600));
        setPreferredSize(new java.awt.Dimension(729, 351));

        jPanel5.setBackground(java.awt.Color.darkGray);
        jPanel5.setMaximumSize(new java.awt.Dimension(940, 700));
        jPanel5.setMinimumSize(new java.awt.Dimension(940, 700));
        jPanel5.setPreferredSize(new java.awt.Dimension(940, 800));

        btnadd2.setBackground(new java.awt.Color(255, 255, 255));
        btnadd2.setText("Update Details");
        btnadd2.setMaximumSize(new java.awt.Dimension(140, 47));
        btnadd2.setMinimumSize(new java.awt.Dimension(140, 47));
        btnadd2.setPreferredSize(new java.awt.Dimension(140, 47));
        btnadd2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnadd2ActionPerformed(evt);
            }
        });

        jLabel45.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel45.setForeground(new java.awt.Color(255, 255, 255));
        jLabel45.setText("Supplier ID");

        jLabel46.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel46.setForeground(new java.awt.Color(255, 255, 255));
        jLabel46.setText("Name");

        jLabel47.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel47.setForeground(new java.awt.Color(255, 255, 255));
        jLabel47.setText("Contact No.");

        jLabel48.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel48.setForeground(new java.awt.Color(255, 255, 255));
        jLabel48.setText("Address");

        jLabel50.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel50.setForeground(new java.awt.Color(255, 255, 255));
        jLabel50.setText("Email");

        btn_Invetory_view5.setBackground(new java.awt.Color(255, 255, 255));
        btn_Invetory_view5.setText("Delete Details");
        btn_Invetory_view5.setMaximumSize(new java.awt.Dimension(140, 47));
        btn_Invetory_view5.setMinimumSize(new java.awt.Dimension(140, 47));
        btn_Invetory_view5.setPreferredSize(new java.awt.Dimension(140, 47));
        btn_Invetory_view5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Invetory_view5ActionPerformed(evt);
            }
        });

        txt_Supplier_cNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_Supplier_cNoActionPerformed(evt);
            }
        });

        txt_Supplier_Email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_Supplier_EmailActionPerformed(evt);
            }
        });

        txt_Supplier_Address.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_Supplier_AddressActionPerformed(evt);
            }
        });

        btnadd5.setBackground(new java.awt.Color(255, 255, 255));
        btnadd5.setText("Search");
        btnadd5.setMaximumSize(new java.awt.Dimension(140, 47));
        btnadd5.setMinimumSize(new java.awt.Dimension(140, 47));
        btnadd5.setPreferredSize(new java.awt.Dimension(140, 47));
        btnadd5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnadd5ActionPerformed(evt);
            }
        });

        cmb_Supplier_Add.setEditable(true);
        cmb_Supplier_Add.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Raw Materials", "Machineries", "Equipments" }));

        jLabel49.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel49.setForeground(new java.awt.Color(255, 255, 255));
        jLabel49.setText("Type");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel50, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel48, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel47, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel46, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel45, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_Supplier_Address, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_Supplier_name, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_Supplier_cNo, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(txt_Supplier_SID, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnadd5, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(txt_Supplier_Email, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(221, 221, 221)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnadd2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_Invetory_view5, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(jLabel49)
                        .addGap(39, 39, 39)
                        .addComponent(cmb_Supplier_Add, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btn_Invetory_view5, btnadd2});

        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnadd5, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cmb_Supplier_Add, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel49))
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel45)
                        .addComponent(txt_Supplier_SID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(13, 13, 13)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(btnadd2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_Invetory_view5, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel46)
                            .addComponent(txt_Supplier_name, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_Supplier_cNo, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel47))
                        .addGap(22, 22, 22)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel48)
                            .addComponent(txt_Supplier_Address, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_Supplier_Email, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel50))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btn_Invetory_view5, btnadd2});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 717, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_Supplier_AddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_Supplier_AddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_Supplier_AddressActionPerformed

    private void txt_Supplier_EmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_Supplier_EmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_Supplier_EmailActionPerformed

    private void txt_Supplier_cNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_Supplier_cNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_Supplier_cNoActionPerformed

    private void btn_Invetory_view5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Invetory_view5ActionPerformed
        // TODO add your handling code here:
        try {
            Connection con = DataBaseConnection.getDBconnection();
            String queryup = "UPDATE suppliers SET Status=? where SupplierID='" + txt_Supplier_SID.getText() + "'";
            PreparedStatement pst = con.prepareStatement(queryup);

            pst.setInt(1, 0);

            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Deleted Successfully");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }


    }//GEN-LAST:event_btn_Invetory_view5ActionPerformed


    private void btnadd2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnadd2ActionPerformed
        // TODO add your handling code here:
        try {
            try {
                Connection con = DataBaseConnection.getDBconnection();
                String queryup = "UPDATE suppliers SET SupplierID=?, Name=?, Type=?, Contact=?, Address=?, Email=? where SupplierID='" + txt_Supplier_SID.getText() + "'";
                PreparedStatement pst = con.prepareStatement(queryup);

                String contact = txt_Supplier_cNo.getText();
                String supname = txt_Supplier_name.getText();
                String address = txt_Supplier_Address.getText();

                if ((supname.equals("")) || (contact.equals("")) || (address.equals(""))) {

                    JOptionPane.showMessageDialog(null, "Error");
                } else {

                    pst.setString(1, txt_Supplier_SID.getText());
                    pst.setString(2, txt_Supplier_name.getText());
                    pst.setString(3, (cmb_Supplier_Add.getSelectedItem().toString()));
                    pst.setString(4, txt_Supplier_cNo.getText());
                    pst.setString(5, txt_Supplier_Address.getText());
                    pst.setString(6, txt_Supplier_Email.getText());

                    pst.executeUpdate();
                    JOptionPane.showMessageDialog(null, "Updated Successfully");

                }
            } catch (StringIndexOutOfBoundsException e) {
                JOptionPane.showMessageDialog(null, "Please fill the required fields");
            }

        } catch (Exception e) {
            System.out.println(e);
            JOptionPane.showMessageDialog(null, "Error Occured");
        }


    }//GEN-LAST:event_btnadd2ActionPerformed

    private void btnadd5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnadd5ActionPerformed
        // TODO add your handling code here:
        try {

            Connection con = DataBaseConnection.getDBconnection();

            String query = "select SupplierID,Name,Type,Contact,Address,Email from suppliers where SupplierID='" + txt_Supplier_SID.getText() + "'";

            st = con.prepareStatement(query);
            st = con.createStatement();
            rs = st.executeQuery(query);

            if (rs.next()) {
                txt_Supplier_SID.setText(txt_Supplier_SID.getText());
                txt_Supplier_name.setText(rs.getString(2));
                cmb_Supplier_Add.setSelectedItem(rs.getString(3));

                txt_Supplier_cNo.setText(rs.getString(4));

                txt_Supplier_Address.setText(rs.getString(5));

                txt_Supplier_Email.setText(rs.getString(6));

            } else {
                JOptionPane.showMessageDialog(null, "Employee Number Is Invalid.");
            }

        } catch (Exception e) {

            JOptionPane.showMessageDialog(null, e);
        }


    }//GEN-LAST:event_btnadd5ActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Manage_Sup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Manage_Sup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Manage_Sup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Manage_Sup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Manage_Sup().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Invetory_view5;
    private javax.swing.JButton btnadd2;
    private javax.swing.JButton btnadd5;
    private javax.swing.JComboBox<String> cmb_Supplier_Add;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTextField txt_Supplier_Address;
    private javax.swing.JTextField txt_Supplier_Email;
    private javax.swing.JTextField txt_Supplier_SID;
    private javax.swing.JTextField txt_Supplier_cNo;
    private javax.swing.JTextField txt_Supplier_name;
    // End of variables declaration//GEN-END:variables
}
