/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import DataBaseLayer.DataBaseConnection;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLIntegrityConstraintViolationException;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Milan.C.Maduwantha
 */
public class Project_Management extends javax.swing.JInternalFrame {

    private String url;
    private Connection conDB;
    private ResultSet rs;
    private Statement st;

    public javax.swing.JDesktopPane dp_home;

    public Project_Management() {
    }

    public Project_Management(javax.swing.JDesktopPane dp) {
        initComponents();

        this.dp_home = dp;
        String pidcolumn = null;
        String pidnewrecord = null;
        String cidcolumn = null;
        String cidnewrecord = null;

        try {

            Connection con = DataBaseConnection.getDBconnection();
            String query = "select * from projects ORDER BY PID DESC LIMIT 1";
            PreparedStatement ps = con.prepareStatement(query);
            Statement statement = con.createStatement();
            ResultSet resultset = ps.executeQuery(query);

            while (resultset.next()) {

                pidcolumn = resultset.getString(1);

            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error Occured.");
        }

        if (pidcolumn == null) {
            pidnewrecord = "PID100000";
        } else {
            String lastrecordid = pidcolumn.substring(3, 9);
            System.out.print(lastrecordid);
            int newid = Integer.parseInt(lastrecordid);
            int newrecordid = newid + 1;
            String id = Integer.toString(newrecordid);
            pidnewrecord = "PID" + id;
        }
        lbl_pid.setText(pidnewrecord);

        try {

            Connection con = DataBaseConnection.getDBconnection();
            String query = "select * from clients ORDER BY CID DESC LIMIT 1";
            PreparedStatement ps = con.prepareStatement(query);
            Statement statement = con.createStatement();
            ResultSet resultset = ps.executeQuery(query);

            while (resultset.next()) {

                cidcolumn = resultset.getString(1);

            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error Occured.");
        }

        if (cidcolumn == null) {
            cidnewrecord = "CID100000";
        } else {
            String lastrecordid = cidcolumn.substring(3, 9);
            System.out.print(lastrecordid);
            int newid = Integer.parseInt(lastrecordid);
            int newrecordid = newid + 1;
            String id = Integer.toString(newrecordid);
            cidnewrecord = "CID" + id;
        }
        lbl_cid.setText(cidnewrecord);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt_projectName = new javax.swing.JTextField();
        txt_projectLocation = new javax.swing.JTextField();
        txt_boqNo = new javax.swing.JTextField();
        txt_estCost = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        btn_addProjectDetails = new javax.swing.JButton();
        btn_manageProjectDetails = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        btn_empSearch_Search = new javax.swing.JButton();
        btn_Invetory_view = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        txt_clientID1 = new javax.swing.JTextField();
        txt_PID = new javax.swing.JTextField();
        jScrollPane9 = new javax.swing.JScrollPane();
        jTable7 = new javax.swing.JTable();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        lbl_startdate = new javax.swing.JLabel();
        lbl_enddate = new javax.swing.JLabel();
        lbl_pid = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel4 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        txt_clientName = new javax.swing.JTextField();
        txt_clientContactno = new javax.swing.JTextField();
        txt_email = new javax.swing.JTextField();
        txt_clientAddress = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        btn_manageClientDetails = new javax.swing.JButton();
        btn_addClientDetails = new javax.swing.JButton();
        lbl_cid = new javax.swing.JLabel();
        jScrollPane10 = new javax.swing.JScrollPane();
        clienttable = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        text_client = new javax.swing.JTextField();
        btn_empSearch_Search1 = new javax.swing.JButton();
        btn_Invetory_view1 = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Project Management");
        setAutoscrolls(true);
        setMinimumSize(new java.awt.Dimension(962, 600));

        jTabbedPane1.setBackground(java.awt.Color.lightGray);
        jTabbedPane1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jTabbedPane1.setMaximumSize(new java.awt.Dimension(962, 600));
        jTabbedPane1.setMinimumSize(new java.awt.Dimension(962, 1000));
        jTabbedPane1.setPreferredSize(new java.awt.Dimension(962, 1000));

        jScrollPane1.setMinimumSize(new java.awt.Dimension(1000, 600));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(1000, 600));

        jPanel1.setBackground(java.awt.Color.darkGray);
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.setMaximumSize(new java.awt.Dimension(960, 1000));
        jPanel1.setMinimumSize(new java.awt.Dimension(960, 1000));
        jPanel1.setPreferredSize(new java.awt.Dimension(960, 1000));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Project ID");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Project Name");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Location");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Start Date");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("End Date");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Est. Cost");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("BOQ Number");

        btn_addProjectDetails.setBackground(new java.awt.Color(255, 255, 255));
        btn_addProjectDetails.setText("Add Details");
        btn_addProjectDetails.setBorder(null);
        btn_addProjectDetails.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_addProjectDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addProjectDetailsActionPerformed(evt);
            }
        });

        btn_manageProjectDetails.setBackground(new java.awt.Color(255, 255, 255));
        btn_manageProjectDetails.setText("Manage Details");
        btn_manageProjectDetails.setBorder(null);
        btn_manageProjectDetails.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_manageProjectDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_manageProjectDetailsActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Project ID");

        btn_empSearch_Search.setBackground(new java.awt.Color(255, 255, 255));
        btn_empSearch_Search.setText("Search");
        btn_empSearch_Search.setBorder(null);
        btn_empSearch_Search.setMaximumSize(new java.awt.Dimension(35, 35));
        btn_empSearch_Search.setMinimumSize(new java.awt.Dimension(35, 35));
        btn_empSearch_Search.setPreferredSize(new java.awt.Dimension(35, 35));
        btn_empSearch_Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_empSearch_SearchActionPerformed(evt);
            }
        });

        btn_Invetory_view.setBackground(new java.awt.Color(255, 255, 255));
        btn_Invetory_view.setText("View All Details");
        btn_Invetory_view.setMaximumSize(new java.awt.Dimension(140, 47));
        btn_Invetory_view.setMinimumSize(new java.awt.Dimension(140, 47));
        btn_Invetory_view.setPreferredSize(new java.awt.Dimension(140, 47));
        btn_Invetory_view.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Invetory_viewActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Client ID");

        txt_clientID1.setBorder(null);

        jScrollPane9.setMaximumSize(new java.awt.Dimension(755, 432));
        jScrollPane9.setMinimumSize(new java.awt.Dimension(755, 432));
        jScrollPane9.setPreferredSize(new java.awt.Dimension(755, 432));

        jTable7.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "PID", "CID", "Project Name", "Location", "Project Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable7.setMaximumSize(new java.awt.Dimension(750, 470));
        jTable7.setMinimumSize(new java.awt.Dimension(750, 470));
        jTable7.setPreferredSize(new java.awt.Dimension(750, 470));
        jScrollPane9.setViewportView(jTable7);

        jDateChooser1.setBackground(java.awt.Color.darkGray);
        jDateChooser1.setDateFormatString("dd/MM/yyyy");

        jDateChooser2.setBackground(java.awt.Color.darkGray);
        jDateChooser2.setDateFormatString("dd/MM/yyyy");

        lbl_pid.setForeground(java.awt.Color.white);
        lbl_pid.setText("PID");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(jLabel8))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addGap(21, 21, 21)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txt_PID, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btn_empSearch_Search, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_Invetory_view, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txt_estCost)
                                    .addComponent(txt_boqNo)
                                    .addComponent(jDateChooser2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txt_projectLocation)
                                    .addComponent(txt_projectName))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(0, 418, Short.MAX_VALUE)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btn_addProjectDetails, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btn_manageProjectDetails, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(lbl_enddate, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lbl_startdate, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(lbl_pid, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(60, 60, 60)
                                .addComponent(jLabel10)
                                .addGap(28, 28, 28)
                                .addComponent(txt_clientID1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jSeparator1)
                    .addComponent(jScrollPane9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(66, 66, 66))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jDateChooser1, jDateChooser2, txt_boqNo});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel10)
                    .addComponent(txt_clientID1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_pid))
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_projectName, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_projectLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_startdate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jDateChooser2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_enddate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_boqNo, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(btn_addProjectDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btn_manageProjectDetails, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txt_estCost, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6)))
                .addGap(35, 35, 35)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_Invetory_view, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txt_PID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_empSearch_Search, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel8)))
                .addGap(46, 46, 46)
                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(88, 88, 88))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jDateChooser1, jDateChooser2, txt_boqNo});

        jScrollPane1.setViewportView(jPanel1);

        jTabbedPane1.addTab("Project Details", jScrollPane1);

        jScrollPane2.setMinimumSize(new java.awt.Dimension(1000, 600));
        jScrollPane2.setPreferredSize(new java.awt.Dimension(1000, 600));

        jPanel4.setBackground(java.awt.Color.darkGray);
        jPanel4.setMaximumSize(new java.awt.Dimension(962, 600));
        jPanel4.setMinimumSize(new java.awt.Dimension(962, 1000));
        jPanel4.setPreferredSize(new java.awt.Dimension(962, 1000));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Client ID");

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Client Name");

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Address");

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Contact Number");

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Email Address");

        txt_clientName.setBorder(null);

        txt_clientContactno.setBorder(null);

        txt_email.setBorder(null);
        txt_email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_emailActionPerformed(evt);
            }
        });

        txt_clientAddress.setBorder(null);
        txt_clientAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_clientAddressActionPerformed(evt);
            }
        });

        btn_manageClientDetails.setBackground(new java.awt.Color(255, 255, 255));
        btn_manageClientDetails.setText("Manage Details");
        btn_manageClientDetails.setBorder(null);
        btn_manageClientDetails.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_manageClientDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_manageClientDetailsActionPerformed(evt);
            }
        });

        btn_addClientDetails.setBackground(new java.awt.Color(255, 255, 255));
        btn_addClientDetails.setText("Add Details");
        btn_addClientDetails.setBorder(null);
        btn_addClientDetails.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_addClientDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addClientDetailsActionPerformed(evt);
            }
        });

        lbl_cid.setForeground(new java.awt.Color(255, 255, 255));
        lbl_cid.setText("CID");

        jScrollPane10.setMaximumSize(new java.awt.Dimension(755, 432));
        jScrollPane10.setMinimumSize(new java.awt.Dimension(755, 432));
        jScrollPane10.setPreferredSize(new java.awt.Dimension(755, 432));

        clienttable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CID", "Name", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        clienttable.setMaximumSize(new java.awt.Dimension(750, 470));
        clienttable.setMinimumSize(new java.awt.Dimension(750, 470));
        clienttable.setPreferredSize(new java.awt.Dimension(750, 470));
        jScrollPane10.setViewportView(clienttable);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Client ID");

        btn_empSearch_Search1.setBackground(new java.awt.Color(255, 255, 255));
        btn_empSearch_Search1.setText("Search");
        btn_empSearch_Search1.setBorder(null);
        btn_empSearch_Search1.setMaximumSize(new java.awt.Dimension(35, 35));
        btn_empSearch_Search1.setMinimumSize(new java.awt.Dimension(35, 35));
        btn_empSearch_Search1.setPreferredSize(new java.awt.Dimension(35, 35));
        btn_empSearch_Search1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_empSearch_Search1ActionPerformed(evt);
            }
        });

        btn_Invetory_view1.setBackground(new java.awt.Color(255, 255, 255));
        btn_Invetory_view1.setText("View All Details");
        btn_Invetory_view1.setMaximumSize(new java.awt.Dimension(140, 47));
        btn_Invetory_view1.setMinimumSize(new java.awt.Dimension(140, 47));
        btn_Invetory_view1.setPreferredSize(new java.awt.Dimension(140, 47));
        btn_Invetory_view1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Invetory_view1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap(723, Short.MAX_VALUE)
                        .addComponent(btn_manageClientDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.LEADING)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(66, 66, 66)
                                .addComponent(jLabel20))
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel4Layout.createSequentialGroup()
                                    .addGap(82, 82, 82)
                                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel21, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(jLabel11))))
                        .addGap(35, 35, 35)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(text_client, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_email, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGap(0, 340, Short.MAX_VALUE)
                                        .addComponent(btn_addClientDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(btn_empSearch_Search1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btn_Invetory_view1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_cid, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_clientContactno, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(txt_clientAddress, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                                        .addComponent(txt_clientName, javax.swing.GroupLayout.Alignment.LEADING)))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap(57, Short.MAX_VALUE))
        );

        jPanel4Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {text_client, txt_email});

        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(lbl_cid))
                        .addGap(175, 175, 175)
                        .addComponent(btn_addClientDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addContainerGap(100, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(txt_clientName, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19)
                            .addComponent(txt_clientAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txt_clientContactno, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel20)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addGap(72, 72, 72)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel21)
                                    .addComponent(txt_email, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_manageClientDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_Invetory_view1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(text_client, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_empSearch_Search1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(46, 46, 46)
                .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(161, 161, 161))
        );

        jPanel4Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {text_client, txt_email});

        jScrollPane2.setViewportView(jPanel4);

        jTabbedPane1.addTab("Client Details", jScrollPane2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 988, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
 public ArrayList<Userpro> user_project_List() {
        ArrayList<Userpro> user_project_List = new ArrayList<>();
        try {
            Connection con = DataBaseConnection.getDBconnection();

            String query = "SELECT * FROM projects where PID='" + txt_PID.getText() + "'";
            st = con.prepareStatement(query);
            st = con.createStatement();
            rs = st.executeQuery(query);

            Userpro userpro;
            while (rs.next()) {
                System.out.println("kk");
                userpro = new Userpro(rs.getString("PID"), rs.getString("CID"), rs.getString("Projectname"), rs.getString("Location"), rs.getInt("Status"));

                user_project_List.add(userpro);

            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        return user_project_List;
    }

    /*method to retrieve leave details */
    public void projectshowuser() {

        ArrayList<Userpro> list = user_project_List();
        DefaultTableModel model = (DefaultTableModel) jTable7.getModel();
        Object[] row = new Object[5];
        for (int i = 0; i < list.size(); i++) {
            row[0] = list.get(i).getPID();
            row[1] = list.get(i).getCID();
            row[2] = list.get(i).getProjName();
            row[3] = list.get(i).getLocation();
            row[4] = list.get(i).getPstatus();
            model.addRow(row);

        }

    }

    public ArrayList<Userpro> user_project_Listo() {
        ArrayList<Userpro> user_project_Listo = new ArrayList<>();
        try {
            Connection con = DataBaseConnection.getDBconnection();

            String query = "SELECT * FROM projects where Status = 1";
            st = con.prepareStatement(query);
            st = con.createStatement();
            rs = st.executeQuery(query);

            Userpro userpro;
            while (rs.next()) {

                userpro = new Userpro(rs.getString("PID"), rs.getString("CID"), rs.getString("Projectname"), rs.getString("Location"), rs.getInt("Status"));

                user_project_Listo.add(userpro);

            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        return user_project_Listo;
    }

    /*method to retrieve leave details */
    public void projectshowusero() {

        ArrayList<Userpro> list = user_project_Listo();
        DefaultTableModel model = (DefaultTableModel) jTable7.getModel();
        Object[] row = new Object[5];
        for (int i = 0; i < list.size(); i++) {
            row[0] = list.get(i).getPID();
            row[1] = list.get(i).getCID();
            row[2] = list.get(i).getProjName();
            row[3] = list.get(i).getLocation();
            row[4] = list.get(i).getPstatus();
            model.addRow(row);

        }

    }

    public ArrayList<Clientdetailone> user_client_List() {
        ArrayList<Clientdetailone> user_client_List = new ArrayList<>();
        try {

            Connection con = DataBaseConnection.getDBconnection();

            String query = "SELECT * FROM clients where CID='" + text_client.getText() + "'";
            st = con.prepareStatement(query);
            st = con.createStatement();
            rs = st.executeQuery(query);

            Clientdetailone clientdetailone;
            while (rs.next()) {
                clientdetailone = new Clientdetailone(rs.getString("CID"), rs.getString("Name"), rs.getInt("Status"));

                user_client_List.add(clientdetailone);

            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "System error occured");
        }
        return user_client_List;
    }

    /*method to retrieve leave details */
    public void allshowuserclient() {

        ArrayList<Clientdetailone> list = user_client_List();
        DefaultTableModel model = (DefaultTableModel) clienttable.getModel();
        Object[] row = new Object[3];
        for (int i = 0; i < list.size(); i++) {
            row[0] = list.get(i).getCID();
            row[1] = list.get(i).getClientName();
            row[2] = list.get(i).getStatus();
            model.addRow(row);

        }
    }

    public ArrayList<Clientdetailone> user_client_List2() {
        ArrayList<Clientdetailone> user_client_List2 = new ArrayList<>();
        try {

            Connection con = DataBaseConnection.getDBconnection();

            String query = "SELECT * FROM clients where Status = 1";
            st = con.prepareStatement(query);
            st = con.createStatement();
            rs = st.executeQuery(query);

            Clientdetailone clientdetailone;
            while (rs.next()) {
                clientdetailone = new Clientdetailone(rs.getString("CID"), rs.getString("Name"), rs.getInt("Status"));

                user_client_List2.add(clientdetailone);

            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "System error occured");
        }
        return user_client_List2;
    }

    /*method to retrieve leave details */
    public void allshowuserclient2() {

        ArrayList<Clientdetailone> list = user_client_List();
        DefaultTableModel model = (DefaultTableModel) clienttable.getModel();
        Object[] row = new Object[3];
        for (int i = 0; i < list.size(); i++) {
            row[0] = list.get(i).getCID();
            row[1] = list.get(i).getClientName();
            row[2] = list.get(i).getStatus();
            model.addRow(row);

        }
    }


    private void btn_empSearch_SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_empSearch_SearchActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) jTable7.getModel();
        model.setRowCount(0);
        user_project_List();
        projectshowuser();
    }//GEN-LAST:event_btn_empSearch_SearchActionPerformed

    private void btn_addProjectDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addProjectDetailsActionPerformed
        // TODO add your handling code here:
        String columnValue = null;
        String recordid = null;
        String newrecord = null;
        try {
            try {

                try {

                    Connection con = DataBaseConnection.getDBconnection();
                    String query = "select * from projects ORDER BY PID DESC LIMIT 1";
                    PreparedStatement ps = con.prepareStatement(query);
                    Statement statement = con.createStatement();
                    ResultSet resultset = ps.executeQuery(query);

                    while (resultset.next()) {

                        columnValue = resultset.getString(1);
                        System.out.print(columnValue);

                    }

                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, "Error Occured.");
                }

                if (columnValue == null) {
                    newrecord = "PID100000";
                } else {
                    String lastrecordid = columnValue.substring(3, 9);
                    System.out.print(lastrecordid);
                    int newid = Integer.parseInt(lastrecordid);
                    int newrecordid = newid + 1;
                    String id = Integer.toString(newrecordid);
                    newrecord = "PID" + id;
                }

                try {
                    Connection con = DataBaseConnection.getDBconnection();
                    String query = "insert into projects(PID, CID, Projectname, Location, Startdate, Enddate, BOQ, Cost, Status) values(?,?,?,?,?,?,?,?,?)";
                    PreparedStatement pst = con.prepareStatement(query);

                    String pname = txt_projectName.getText();
                    String client = txt_clientID1.getText();
                    String location = txt_projectLocation.getText();
                    String boq = txt_boqNo.getText();

                    if ((pname.equals("")) || (client.equals("")) || (location.equals("")) || (boq.equals(""))) {
                        JOptionPane.showMessageDialog(null, "Error");
                    } else {

                        pst.setString(1, newrecord);
                        pst.setString(2, txt_clientID1.getText());
                        pst.setString(3, txt_projectName.getText());
                        pst.setString(4, txt_projectLocation.getText());
                        pst.setString(5, ((JTextField) jDateChooser1.getDateEditor().getUiComponent()).getText());
                        pst.setString(6, ((JTextField) jDateChooser2.getDateEditor().getUiComponent()).getText());
                        pst.setString(7, txt_boqNo.getText());
                        String er = txt_estCost.getText();
                        int q = Integer.parseInt(er);

                        pst.setInt(8, q);

                        pst.setInt(9, 1);

                        pst.executeUpdate();
                        JOptionPane.showMessageDialog(null, "inserted successfully");
                    }
                } catch (SQLIntegrityConstraintViolationException e) {
                    System.out.println("history already exist");
                }

            } catch (StringIndexOutOfBoundsException e) {
                JOptionPane.showMessageDialog(null, "Please fill the required fields");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);

        }


    }//GEN-LAST:event_btn_addProjectDetailsActionPerformed

    private void btn_addClientDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addClientDetailsActionPerformed
        // TODO add your handling code here:
        String columnValue = null;
        String recordid = null;
        String newrecord = null;

        try {

            Connection con = DataBaseConnection.getDBconnection();
            String query = "select * from clients ORDER BY CID DESC LIMIT 1";
            PreparedStatement ps = con.prepareStatement(query);
            Statement statement = con.createStatement();
            ResultSet resultset = ps.executeQuery(query);

            while (resultset.next()) {

                columnValue = resultset.getString(1);
                System.out.print(columnValue);

            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error Occured.");
        }

        if (columnValue == null) {
            newrecord = "CID100000";
        } else {
            String lastrecordid = columnValue.substring(3, 9);
            System.out.print(lastrecordid);
            int newid = Integer.parseInt(lastrecordid);
            int newrecordid = newid + 1;
            String id = Integer.toString(newrecordid);
            newrecord = "CID" + id;
        }

        try {

            Connection con = DataBaseConnection.getDBconnection();
            String query = "insert into clients (CID, Name, Address, Contact, Email, Status) values(?,?,?,?,?,?)";
            PreparedStatement pst = con.prepareStatement(query);

            pst.setString(1, newrecord);
            pst.setString(2, txt_clientName.getText());
            pst.setString(3, txt_clientAddress.getText());
            pst.setString(4, txt_clientContactno.getText());
            pst.setString(5, txt_email.getText());
            pst.setInt(6, 1);

            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "inserted successfully");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Please fill the required fields");

        }


    }//GEN-LAST:event_btn_addClientDetailsActionPerformed

    private void txt_clientAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_clientAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_clientAddressActionPerformed

    private void txt_emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_emailActionPerformed

    private void btn_manageProjectDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_manageProjectDetailsActionPerformed
        // TODO add your handling code here:
        Manage_Projects mpr = new Manage_Projects();
        dp_home.add(mpr).setVisible(true);

    }//GEN-LAST:event_btn_manageProjectDetailsActionPerformed

    private void btn_Invetory_viewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Invetory_viewActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) jTable7.getModel();
        model.setRowCount(0);
        user_project_Listo();
        projectshowusero();


    }//GEN-LAST:event_btn_Invetory_viewActionPerformed

    private void btn_manageClientDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_manageClientDetailsActionPerformed
        // TODO add your handling code here:
        Manage_Clients mcl = new Manage_Clients();
        dp_home.add(mcl).setVisible(true);
    }//GEN-LAST:event_btn_manageClientDetailsActionPerformed

    private void btn_empSearch_Search1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_empSearch_Search1ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) clienttable.getModel();
        model.setRowCount(0);
        user_client_List();
        allshowuserclient();
    }//GEN-LAST:event_btn_empSearch_Search1ActionPerformed

    private void btn_Invetory_view1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Invetory_view1ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) clienttable.getModel();
        model.setRowCount(0);
        user_client_List2();
        allshowuserclient2();
    }//GEN-LAST:event_btn_Invetory_view1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Project_Management.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Project_Management.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Project_Management.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Project_Management.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Project_Management().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Invetory_view;
    private javax.swing.JButton btn_Invetory_view1;
    private javax.swing.JButton btn_addClientDetails;
    private javax.swing.JButton btn_addProjectDetails;
    private javax.swing.JButton btn_empSearch_Search;
    private javax.swing.JButton btn_empSearch_Search1;
    private javax.swing.JButton btn_manageClientDetails;
    private javax.swing.JButton btn_manageProjectDetails;
    private javax.swing.JTable clienttable;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable7;
    private javax.swing.JLabel lbl_cid;
    private javax.swing.JLabel lbl_enddate;
    private javax.swing.JLabel lbl_pid;
    private javax.swing.JLabel lbl_startdate;
    private javax.swing.JTextField text_client;
    private javax.swing.JTextField txt_PID;
    private javax.swing.JTextField txt_boqNo;
    private javax.swing.JTextField txt_clientAddress;
    private javax.swing.JTextField txt_clientContactno;
    private javax.swing.JTextField txt_clientID1;
    private javax.swing.JTextField txt_clientName;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_estCost;
    private javax.swing.JTextField txt_projectLocation;
    private javax.swing.JTextField txt_projectName;
    // End of variables declaration//GEN-END:variables
}
